### ISSUE TITLE
Tìm hiểu công nghệ sử dụng trong đề tài 

### ISSUE THREAD

**Issue by 1wku** [PhuongVy20110232/Nhom9_CCvMT#1]

**Comment by PhuongVy20110232** [comment]
1. Phần cứng:​ Chưa thống nhất 
2. Phần mềm:​ Visual Studio Code, Intellij… 
3. Công cụ phát triển​ 
- Ngôn ngữ sử dụng: HTML, CSS, ReactJs, Java, Spring Boot. 
- Hệ cơ sở dữ liệu: MySQL
